version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - "jimbrig"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jimbrig"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "monthly"
    assignees:
      - "jimbrig"
